In [2]:
# importação das bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('CPI2023.csv')
data

,Country,Territory,ISO3,Region,CPI score 2023,Rank,Standard error,Number of sources,Lower CI,Upper CI,...,Economist Intelligence Unit Country Ratings,Freedom House Nations in Transit,Global Insights Country Risk Ratings,IMD World Competitiveness Yearbook,PERC Asia Risk Guide,PRS International Country Risk Guide,Varieties of Democracy Project,World Bank CPIA,World Economic Forum EOS,World Justice Project Rule of Law Index
0,Denmark,DNK,WE/EU,90,1,1.819265,8.0,87.016400,92.98360,NaN,...,NaN,83.25637,97.89119,NaN,100.000000,78.891520,NaN,82.20667,87.680970,NaN
1,Finland,FIN,WE/EU,87,2,1.057962,8.0,85.264950,88.73505,NaN,...,NaN,83.25637,89.84466,NaN,93.380180,78.168110,NaN,86.76612,85.884410,NaN
2,New Zealand,NZL,AP,85,3,1.916107,8.0,81.857580,88.14242,NaN,...,NaN,83.25637,87.10542,NaN,93.380180,78.168110,NaN,70.98344,82.291300,NaN
3,Norway,NOR,WE/EU,84,4,1.380803,7.0,81.735480,86.26452,NaN,...,NaN,83.25637,75.72045,NaN,84.671390,78.168110,NaN,NaN,86.782680,NaN
4,Singapore,SGP,AP,83,5,1.145734,9.0,81.120990,84.87901,NaN,...,NaN,83.25637,76.74767,89.29896,83.277980,78.168110,NaN,88.51975,84.087850,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Yemen,YEM,MENA,16,176,1.753443,7.0,13.124350,18.87565,NaN,...,NaN,10.21805,NaN,NaN,15.001060,13.061650,10.11772,28.54554,NaN,NaN
176,South Sudan,SSD,SSA,13,177,1.328441,5.0,10.821360,15.17864,11.191160,...,NaN,10.21805,NaN,NaN,NaN,18.848890,10.11772,NaN,NaN,NaN
177,Syria,SYR,MENA,13,177,1.578473,5.0,10.411300,15.58870,NaN,...,NaN,10.21805,NaN,NaN,15.001060,12.338250,NaN,NaN,NaN,NaN
178,Venezuela,VEN,AME,13,177,1.226027,8.0,10.989320,15.01068,NaN,...,NaN,10.21805,22.21965,NaN,12.910950,8.721219,NaN,16.27012,8.632427,NaN
179,Somalia,SOM,SSA,11,180,2.077071,6.0,7.593603,14.40640,3.530485,...,NaN,22.45197,NaN,NaN,6.292267,13.785060,10.11772,NaN,NaN,NaN

In [4]:
# assume 'data' is a pandas dataframe with the header data
plt.bar(data['Country'], data['CPI score 2023'])
plt.xlabel('Country')
plt.ylabel('CPI score 2023')
plt.title('Comparison of CPI scores between countries')
plt.show()

KeyError: 'Country'

In [ ]:
# assume 'data' is a pandas dataframe with the header data
plt.boxplot([data[data['Region'] == region]['CPI score 2023'] for region in data['Region'].unique()])
plt.xlabel('Region')
plt.ylabel('CPI score 2023')
plt.title('Distribution of CPI scores by region')
plt.show()

In [ ]:
# assume 'data' is a pandas dataframe with the header data
plt.scatter(data['Rank'], data['Economist Intelligence Unit Country Ratings'])
plt.xlabel('CPI Rank')
plt.ylabel('Economist Intelligence Unit Country Ratings')
plt.title('Comparison of rankings between sources')
plt.show()

In [ ]:
# assume 'data' is a pandas dataframe with the header data
plt.scatter(data['CPI score 2023'], data['IMD World Competitiveness Yearbook'])
plt.xlabel('CPI score 2023')
plt.ylabel('IMD World Competitiveness Yearbook')
plt.title('Correlation analysis between CPI and other variables')
plt.show()